spring.application.name=SE193114HotelGateway
server.port=8080

spring.cloud.gateway.server.webmvc.routes[0].id=room-service
spring.cloud.gateway.server.webmvc.routes[0].uri=http://localhost:8081
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/api/rooms/**
spring.cloud.gateway.server.webmvc.routes[1].id=reservation-service
spring.cloud.gateway.server.webmvc.routes[1].uri=http://localhost:8082
spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=Path=/api/reservations/**

spring.cloud.gateway.server.webmvc.routes[2].id=room-docs
spring.cloud.gateway.server.webmvc.routes[2].uri=http://localhost:8081
spring.cloud.gateway.server.webmvc.routes[2].predicates[0]=Path=/docs/room
spring.cloud.gateway.server.webmvc.routes[2].filters[0]=SetPath=/v3/api-docs
spring.cloud.gateway.server.webmvc.routes[3].id=reservation-docs
spring.cloud.gateway.server.webmvc.routes[3].uri=http://localhost:8082
spring.cloud.gateway.server.webmvc.routes[3].predicates[0]=Path=/docs/reservation
spring.cloud.gateway.server.webmvc.routes[3].filters[0]=SetPath=/v3/api-docs


springdoc.swagger-ui.urls[0].name=room-service (8081)
springdoc.swagger-ui.urls[0].url=/docs/room
springdoc.swagger-ui.urls[1].name=reservation-service (8082)
springdoc.swagger-ui.urls[1].url=/docs/reservation
