spring.application.name=SE193114Gateway
server.port=8080

spring.cloud.gateway.server.webmvc.routes[0].id=master-service
spring.cloud.gateway.server.webmvc.routes[0].uri=http://localhost:8081
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/api/masters/**
spring.cloud.gateway.server.webmvc.routes[1].id=detail-service
spring.cloud.gateway.server.webmvc.routes[1].uri=http://localhost:8082
spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=Path=/api/details/**

spring.cloud.gateway.server.webmvc.routes[2].id=master-docs
spring.cloud.gateway.server.webmvc.routes[2].uri=http://localhost:8081
spring.cloud.gateway.server.webmvc.routes[2].predicates[0]=Path=/docs/master
spring.cloud.gateway.server.webmvc.routes[2].filters[0]=SetPath=/v3/api-docs
spring.cloud.gateway.server.webmvc.routes[3].id=detail-docs
spring.cloud.gateway.server.webmvc.routes[3].uri=http://localhost:8082
spring.cloud.gateway.server.webmvc.routes[3].predicates[0]=Path=/docs/detail
spring.cloud.gateway.server.webmvc.routes[3].filters[0]=SetPath=/v3/api-docs

spring.cloud.gateway.server.webmvc.routes[4].id=category-service
spring.cloud.gateway.server.webmvc.routes[4].uri=http://localhost:8081
spring.cloud.gateway.server.webmvc.routes[4].predicates[0]=Path=/api/categories/**

springdoc.swagger-ui.urls[0].name=master-service (8081)
springdoc.swagger-ui.urls[0].url=/docs/master
springdoc.swagger-ui.urls[1].name=detail-service (8082)
springdoc.swagger-ui.urls[1].url=/docs/detail
